package com.example.book.BookMaster.models;

public enum ProviderType {
	HEALTHCARE,
    BEAUTY_AND_PERSONAL_CARE,
    HOME_SERVICES,
    FITNESS_AND_WELLNESS,
    EVENT_PLANNING_AND_ENTERTAINMENT,
    AUTOMOTIVE_SERVICES,
    EDUCATION_AND_TUTORING,
    TRAVEL_AND_LEISURE,
    LEGAL_AND_FINANCIAL_SERVICES,
    FOOD_AND_DRINK,
    PHOTOGRAPHY_AND_VIDEOGRAPHY;
}
